% -------------------------------------------------------------------
%  Generated by MATLAB on 25-Aug-2015 21:50:43
%  MATLAB version: 8.3.0.532 (R2014a)
% -------------------------------------------------------------------
                                          

fuzzy_bike_sug = struct;
fuzzy_bike_sug.name = 'fuzzy_bike_sug';
fuzzy_bike_sug.type = 'sugeno';
fuzzy_bike_sug.andMethod = 'min';
fuzzy_bike_sug.orMethod = 'max';
fuzzy_bike_sug.defuzzMethod = 'wtaver';
fuzzy_bike_sug.impMethod = 'prod';
fuzzy_bike_sug.aggMethod = 'sum';
fuzzy_bike_sug.input = struct;
fuzzy_bike_sug.input(1).name = 'Velocity';
fuzzy_bike_sug.input(1).range = [0 10];
fuzzy_bike_sug.input(1).mf = struct;
fuzzy_bike_sug.input(1).mf(1).name = 'Slow';
fuzzy_bike_sug.input(1).mf(1).type = 'gaussmf';
fuzzy_bike_sug.input(1).mf(1).params = ...
  [2.083 0];
fuzzy_bike_sug.input(1).mf(2).name = 'Med';
fuzzy_bike_sug.input(1).mf(2).type = 'gaussmf';
fuzzy_bike_sug.input(1).mf(2).params = ...
  [2.083 5];
fuzzy_bike_sug.input(1).mf(3).name = 'Fast';
fuzzy_bike_sug.input(1).mf(3).type = 'gaussmf';
fuzzy_bike_sug.input(1).mf(3).params = ...
  [2.083 10];
fuzzy_bike_sug.input(2).name = 'Distance';
fuzzy_bike_sug.input(2).range = [0 40];
fuzzy_bike_sug.input(2).mf = struct;
fuzzy_bike_sug.input(2).mf(1).name = 'Close';
fuzzy_bike_sug.input(2).mf(1).type = 'gaussmf';
fuzzy_bike_sug.input(2).mf(1).params = ...
  [8.5 0];
fuzzy_bike_sug.input(2).mf(2).name = 'Med';
fuzzy_bike_sug.input(2).mf(2).type = 'gaussmf';
fuzzy_bike_sug.input(2).mf(2).params = ...
  [8.5 20];
fuzzy_bike_sug.input(2).mf(3).name = 'Far';
fuzzy_bike_sug.input(2).mf(3).type = 'gaussmf';
fuzzy_bike_sug.input(2).mf(3).params = ...
  [8.5 40];
fuzzy_bike_sug.output = struct;
fuzzy_bike_sug.output.name = 'PWM';
fuzzy_bike_sug.output.range = [0 255];
fuzzy_bike_sug.output.mf = struct;
fuzzy_bike_sug.output.mf(1).name = 'Low';
fuzzy_bike_sug.output.mf(1).type = 'linear';
fuzzy_bike_sug.output.mf(1).params = ...
  [0 0 41.65];
fuzzy_bike_sug.output.mf(2).name = 'Med';
fuzzy_bike_sug.output.mf(2).type = 'linear';
fuzzy_bike_sug.output.mf(2).params = ...
  [0 0 127.5];
fuzzy_bike_sug.output.mf(3).name = 'High';
fuzzy_bike_sug.output.mf(3).type = 'linear';
fuzzy_bike_sug.output.mf(3).params = ...
  [0 0 255];
fuzzy_bike_sug.rule = struct;
fuzzy_bike_sug.rule(1).antecedent = ...
  [1 1];
fuzzy_bike_sug.rule(1).consequent = 2;
fuzzy_bike_sug.rule(1).weight = 1;
fuzzy_bike_sug.rule(1).connection = 1;
fuzzy_bike_sug.rule(2).antecedent = ...
  [1 2];
fuzzy_bike_sug.rule(2).consequent = 1;
fuzzy_bike_sug.rule(2).weight = 1;
fuzzy_bike_sug.rule(2).connection = 1;
fuzzy_bike_sug.rule(3).antecedent = ...
  [1 3];
fuzzy_bike_sug.rule(3).consequent = 1;
fuzzy_bike_sug.rule(3).weight = 1;
fuzzy_bike_sug.rule(3).connection = 1;
fuzzy_bike_sug.rule(4).antecedent = ...
  [2 1];
fuzzy_bike_sug.rule(4).consequent = 3;
fuzzy_bike_sug.rule(4).weight = 1;
fuzzy_bike_sug.rule(4).connection = 1;
fuzzy_bike_sug.rule(5).antecedent = ...
  [2 2];
fuzzy_bike_sug.rule(5).consequent = 2;
fuzzy_bike_sug.rule(5).weight = 1;
fuzzy_bike_sug.rule(5).connection = 1;
fuzzy_bike_sug.rule(6).antecedent = ...
  [2 3];
fuzzy_bike_sug.rule(6).consequent = 1;
fuzzy_bike_sug.rule(6).weight = 1;
fuzzy_bike_sug.rule(6).connection = 1;
fuzzy_bike_sug.rule(7).antecedent = ...
  [3 1];
fuzzy_bike_sug.rule(7).consequent = 3;
fuzzy_bike_sug.rule(7).weight = 1;
fuzzy_bike_sug.rule(7).connection = 1;
fuzzy_bike_sug.rule(8).antecedent = ...
  [3 2];
fuzzy_bike_sug.rule(8).consequent = 3;
fuzzy_bike_sug.rule(8).weight = 1;
fuzzy_bike_sug.rule(8).connection = 1;
fuzzy_bike_sug.rule(9).antecedent = ...
  [3 3];
fuzzy_bike_sug.rule(9).consequent = 2;
fuzzy_bike_sug.rule(9).weight = 1;
fuzzy_bike_sug.rule(9).connection = 1;

